use_default_settings: true

server:
  limiter: false
  image_proxy: true
  bind_address: "0.0.0.0:8080"

ui:
  static_use_hash: true
  default_locale: en
  theme_args:
    simple_style: dark

search:
  safe_search: 0
  autocomplete: ""
  default_lang: "auto"
  formats:
    - html
    - json

engines:
  - name: google
    disabled: false
  - name: bing
    disabled: false
  - name: duckduckgo
    disabled: false
  - name: wikipedia
    disabled: false
  - name: github
    disabled: false
